#!/bin/bash
set -e

###################################################################################################################################
#							OPTIONS

# Distribution for rootfs
# - buildroot
# - debian
: ${DISTRO:=buildroot}

# Target Board
# - evm: TI TMDS64GPEVM AM64 EVK
# - hummingboard-t: SolidRun AM6442 HummingBoard T
: ${BOARD:=hummingboard-t}

# Silicon Revision
# - sr1: AM6442A - SR 1.0
# - sr2: AM6442B - SR 2.0
: ${SOC_VERSION:=sr1}

# Silicon Type
# - gp: general purpose (ONLY sr1)
# - hs-fs: high security, field-securable (before burning customer key to efuses, sr2 and later only)
# - hs-se: high security, security enabled (after burning customer key to efuses, sr2 and later only)
: ${SOC_TYPE:=gp}

# Kernel Modules:
# including all modules results in large image size - list here the ones to include by default;
# list can easily be generated by "lsmod | cut -d ' ' -f 1 | sort | tr '\n' ','"
: ${MODULES:=at24,authenc,bluetooth,btbcm,btintel,btrtl,btusb,can_dev,cdns3,cdns3_ti,cfg80211,crct10dif_ce,ecc,ecdh_generic,fuse,hdc2010,icss_iep,icssg_prueth,ip_tables,ipv6,irq_pruss_intc,iwlmvm,iwlwifi,libarc4,m_can,m_can_platform,mac80211,opt3001,pci_endpoint_test,pru_rproc,pruss,qcserial,rfkill,rtc_abx80x,rti_wdt,sa2ul,sha512_generic,ti_k3_m4_remoteproc,ti_k3_r5_remoteproc,udc_core,usb_storage,usb_wwan,usbcore,x_tables,usbserial,xhci_hcd,xhci_plat_hcd}

## Buildroot Options
: ${BUILDROOT_VERSION:=2023.02.6}
: ${BUILDROOT_DEFCONFIG:=am64xx_solidrun_defconfig}
: ${BR2_PRIMARY_SITE:=}

## Debian Options
: ${DEBIAN_VERSION:=bullseye}
: ${DEBIAN_ROOTFS_SIZE:=936M}

###################################################################################################################################

# Check if git user name and git email are configured
if [ -z "`git config user.name`" ] || [ -z "`git config user.email`" ]; then
			echo "git is not configured, please run:"
			echo "git config --global user.email \"you@example.com\""
			echo "git config --global user.name \"Your Name\""
			exit -1
fi


BASE_DIR=`pwd`


export CROSS_COMPILE=aarch64-none-linux-gnu-
export ARCH=arm64
export PATH=$BASE_DIR/build/toolchain/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu/bin:$PATH


mkdir -p $BASE_DIR/build

# Get number of jobs in this machine to use with make command
JOBS=$(getconf _NPROCESSORS_ONLN)

# get commit hash
COMMIT_HASH=`git log -1 --pretty=format:%h`

###################################################################################################################################
#                                                       INSTALL Packages

PACKAGES_LIST="bc bison build-essential ca-certificates cpio crossbuild-essential-arm64 crossbuild-essential-armhf debootstrap device-tree-compiler e2tools fakeroot fdisk flex git kmod libncurses-dev libssl-dev make mtools parted python3-dev python3-pyelftools qemu-system-arm rsync sudo swig u-boot-tools unzip wget xz-utils"

set +e
for i in $PACKAGES_LIST; do

	#Check if package is installed
	dpkg -s $i > /dev/null  2>&1

	#If exit code is not 0 - package is not installed
	if [ $? -ne 0 ]; then


		echo "Package $i is not installed"
		echo "If using apt package manager, you can install this tool using:"
		echo "	sudo apt install $i"
		echo "You can install all needed packages using:"
		echo "	sudo apt install $PACKAGES_LIST"

		exit -1
	fi

done

# Check if needed Python modules are installed

PYTHON_MODULES="pycryptodome"

for i in $PYTHON_MODULES; do

        #Check if module is installed
        pip3 list | grep $i > /dev/null 2>&1

        #If exit code is not 0 - module is not installed
        if [ $? -ne 0 ]; then


                echo "Python module $i is not installed"
                echo "Please install it using:"
                echo "  pip3 install $i"

                exit -1
        fi

done

set -e

###################################################################################################################################




###################################################################################################################################
#							DOWNLOAD Toolchain

if [[ ! -d $BASE_DIR/build/toolchain ]]; then
	mkdir $BASE_DIR/build/toolchain
	cd $BASE_DIR/build/toolchain
	wget https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz
	tar -xvf gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz
fi

###################################################################################################################################




###################################################################################################################################
#							CLONE K3 Image Gen
IMAGE_GEN_TAG=08.06.00.007

if [[ ! -d $BASE_DIR/build/k3-image-gen ]]; then
	cd $BASE_DIR/build
	git clone git://git.ti.com/k3-image-gen/k3-image-gen.git -b $IMAGE_GEN_TAG --depth=1
fi

###################################################################################################################################




###################################################################################################################################
#							CLONE ATF
ATF_TAG=08.06.00.007

if [[ ! -d $BASE_DIR/build/arm-trusted-firmware ]]; then
	cd $BASE_DIR/build
	git clone git://git.ti.com/atf/arm-trusted-firmware.git -b $ATF_TAG --depth=1
fi

###################################################################################################################################




###################################################################################################################################
#							CLONE OPTEE
OPTEE_HASH=e4ca953c381e176bafe5a703c0cd18dd21aa5af5

if [[ ! -d $BASE_DIR/build/optee_os ]]; then
	cd $BASE_DIR/build
	git clone https://github.com/OP-TEE/optee_os.git
	cd optee_os
	git reset --hard $OPTEE_HASH
fi

###################################################################################################################################




###################################################################################################################################
#							CLONE U-boot
U_BOOT_TAG=08.06.00.007

if [[ ! -d $BASE_DIR/build/ti-u-boot ]]; then
	cd $BASE_DIR/build
	git clone git://git.ti.com/ti-u-boot/ti-u-boot.git -b $U_BOOT_TAG --depth=1
	cd ti-u-boot
	git am $BASE_DIR/patches/uboot/*.patch

fi

###################################################################################################################################




###################################################################################################################################
#							CLONE k3conf Tool
K3CONF_BRANCH=master
K3CONF_HEAD=982f5c2f02f732b5829861218812904cd776773d

if [[ ! -d $BASE_DIR/build/k3conf ]]; then
	cd $BASE_DIR/build
	git clone git://git.ti.com/k3conf/k3conf.git -b $K3CONF_BRANCH
	cd k3conf
	git reset --hard $K3CONF_HEAD
	test -d $BASE_DIR/patches/k3conf && git am $BASE_DIR/patches/k3conf/*.patch
fi

###################################################################################################################################




###################################################################################################################################
#							CLONE Security Development Package
SECDEVPKG_BRANCH=master
SECDEVPKG_HEAD=08.06.00.007

if [[ ! -d $BASE_DIR/build/core-secdev-k3 ]]; then
	cd $BASE_DIR/build
	git clone git://git.ti.com/security-development-tools/core-secdev-k3.git -b $SECDEVPKG_BRANCH
	cd core-secdev-k3
	git reset --hard $SECDEVPKG_HEAD
	test -d $BASE_DIR/patches/core-secdev-k3 && git am $BASE_DIR/patches/k3conf/*.patch
fi
export TI_SECURE_DEV_PKG=$BASE_DIR/build/core-secdev-k3

###################################################################################################################################




###################################################################################################################################
#							CLONE Linux Kernel
KERNEL_TAG=08.06.00.007

if [[ ! -d $BASE_DIR/build/ti-linux-kernel ]]; then
	cd $BASE_DIR/build
	git clone git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git	-b $KERNEL_TAG --depth=1
	cd ti-linux-kernel
	git am $BASE_DIR/patches/linux/*.patch
fi

###################################################################################################################################




###################################################################################################################################
#							DOWNLOAD Buildroot
do_fetch_buildroot() {
	if [[ ! -d $BASE_DIR/build/buildroot ]]; then
		cd $BASE_DIR/build
		git clone https://github.com/buildroot/buildroot -b $BUILDROOT_VERSION --depth=1
		cd buildroot
		git am $BASE_DIR/patches/buildroot/*.patch
	fi
}

###################################################################################################################################




###################################################################################################################################
#							DOWNLOAD Debian
do_fetch_debian() {
	# Nothing to do here - will use debootstrap command later
	:
}

###################################################################################################################################




##################################################################################################################################
#							DOWNLOAD selected Distro
do_fetch_${DISTRO}
##################################################################################################################################



mkdir -p $BASE_DIR/tmp




###################################################################################################################################
#							BUILD ATF
PLAT=k3

cd  $BASE_DIR/build/arm-trusted-firmware
make -j${JOBS} CROSS_COMPILE=aarch64-linux-gnu- ARCH=aarch64 PLAT=$PLAT TARGET_BOARD=lite SPD=opteed
cp build/k3/lite/release/bl31.bin $BASE_DIR/tmp/bl31.bin

###################################################################################################################################




###################################################################################################################################
#							BUILD OPTEE
PLATFORM=k3-am64x

cd  $BASE_DIR/build/optee_os
make -j${JOBS} ARCH=arm PLATFORM=$PLATFORM CROSS_COMPILE32=arm-linux-gnueabihf- CFG_ARM64_core=y
cp out/arm-plat-k3/core/tee-pager_v2.bin $BASE_DIR/tmp/tee-pager_v2.bin

###################################################################################################################################




###################################################################################################################################
#							BUILD U-boot

case ${BOARD} in
	evm)
		U_BOOT_R5_DEFCONFIG=am64x_evm_r5_defconfig
		U_BOOT_A53_DEFCONFIG=am64x_evm_a53_defconfig
		;;
	hummingboard-t)
		U_BOOT_R5_DEFCONFIG=am64x_r5_solidrun_defconfig
		U_BOOT_A53_DEFCONFIG=am64x_a53_solidrun_defconfig
		;;
	*)
		echo "ERROR: Board \"${BOARD}\" not supported!"
		exit 1
		;;
esac
cd $BASE_DIR/build/ti-u-boot


# 	R5

make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- $U_BOOT_R5_DEFCONFIG
#make ARCH=arm menuconfig
make ARCH=arm savedefconfig
mv defconfig defconfig_r5
make -j${JOBS} ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
cp spl/u-boot-spl.bin $BASE_DIR/tmp/u-boot-spl.bin



# 	A53

make ARCH=arm CROSS_COMPILE=aarch64-linux-gnu- $U_BOOT_A53_DEFCONFIG
#make ARCH=arm menuconfig
make ARCH=arm savedefconfig
mv defconfig defconfig_a53
make -j${JOBS} ARCH=arm CROSS_COMPILE=aarch64-linux-gnu- ATF=$BASE_DIR/tmp/bl31.bin TEE=$BASE_DIR/tmp/tee-pager_v2.bin


cp tispl.bin $BASE_DIR/tmp/tispl.bin
cp u-boot.img $BASE_DIR/tmp/u-boot.img

###################################################################################################################################




###################################################################################################################################
#							BUILD SYSFW
function do_build_sysfw() {
	case ${SOC_VERSION}_${SOC_TYPE} in
		sr1_gp)
			SOC=am64x
		;;
		sr2_hs-fs|sr2_hs-se)
			SOC=am64x_sr2
		;;
		*)
			echo "Error: Silicon \"${SOC_VERSION}\" type \"${SOC_TYPE}\" is not supported!"
	esac

	cd $BASE_DIR/build/k3-image-gen
	make SOC=$SOC SOC_TYPE=$SOC_TYPE mrproper
	make SOC=$SOC SOC_TYPE=$SOC_TYPE ENABLE_TRACE=1 SBL=$BASE_DIR/tmp/u-boot-spl.bin
	cp tiboot3-${SOC}-${SOC_TYPE}-evm.bin $BASE_DIR/tmp/tiboot3.bin
}
do_build_sysfw
###################################################################################################################################




###################################################################################################################################
#							BUILD k3conf Tool
cd $BASE_DIR/build/k3conf
make
${CROSS_COMPILE}strip --strip-unneeded k3conf
install -v -m755 k3conf $BASE_DIR/tmp/k3conf

###################################################################################################################################




###################################################################################################################################
#							BUILD Linux
LINUX_DEFCONFIG=am64xx-solidrun-linux_defconfig

cd $BASE_DIR/build/ti-linux-kernel
./scripts/kconfig/merge_config.sh -O "${BASE_DIR}/build/ti-linux-kernel" -m arch/arm64/configs/defconfig "${BASE_DIR}/configs/${LINUX_DEFCONFIG}"
make olddefconfig
#make menuconfig
make savedefconfig
make -j${JOBS} dtbs Image modules
rm -rf "${BASE_DIR}/tmp/linux"
mkdir -p "${BASE_DIR}/tmp/linux/boot/ti"
cp arch/arm64/boot/Image "${BASE_DIR}/tmp/linux/boot/Image"
cp arch/arm64/boot/dts/ti/*.dtb "${BASE_DIR}/tmp/linux/boot/ti/"
cp .config "${BASE_DIR}/tmp/linux/boot/config"
cp System.map "${BASE_DIR}/tmp/linux/boot/System.map"
make -j${JOBS} INSTALL_MOD_PATH="${BASE_DIR}/tmp/linux/usr" modules_install

###################################################################################################################################




##################################################################################################################################
#							BUILD Buildroot rootfs
do_build_buildroot() {
	cp $BASE_DIR/configs/am64xx-solidrun-buildroot_defconfig $BASE_DIR/build/buildroot/configs/${BUILDROOT_DEFCONFIG}
	printf 'BR2_PRIMARY_SITE="%s"\n' "${BR2_PRIMARY_SITE}" >> $BASE_DIR/build/buildroot/configs/${BUILDROOT_DEFCONFIG}

	cd $BASE_DIR/build/buildroot
	make $BUILDROOT_DEFCONFIG
	#make menuconfig
	make savedefconfig BR2_DEFCONFIG="${BASE_DIR}/build/buildroot/defconfig"
	make -j${JOBS}

	cp $BASE_DIR/build/buildroot/output/images/rootfs.cpio.uboot $BASE_DIR/tmp/rootfs.cpio
	cp $BASE_DIR/build/buildroot/output/images/rootfs.ext4 $BASE_DIR/tmp/rootfs.ext4
}
###################################################################################################################################




##################################################################################################################################
#							BUILD Debian rootfs
do_build_debian() {
	mkdir -p $BASE_DIR/build/debian
	cd $BASE_DIR/build/debian

	# (re-)generate only if rootfs doesn't exist or runme script has changed
	if [ ! -f rootfs.e2.orig ] || [[ ${BASE_DIR}/${BASH_SOURCE[0]} -nt rootfs.e2.orig ]]; then
		rm -f rootfs.e2.orig

		# bootstrap a first-stage rootfs
		rm -rf stage1
		fakeroot debootstrap --variant=minbase \
			--arch=arm64 --components=main,contrib,non-free \
			--foreign \
			--include=apt-transport-https,busybox,ca-certificates,can-utils,command-not-found,chrony,curl,e2fsprogs,ethtool,fdisk,gpiod,haveged,i2c-tools,ifupdown,iputils-ping,isc-dhcp-client,initramfs-tools,libiio-utils,lm-sensors,locales,nano,net-tools,ntpdate,openssh-server,psmisc,rfkill,sudo,systemd-sysv,tio,usbutils,wget,xterm,xz-utils \
			${DEBIAN_VERSION} \
			stage1 \
			https://deb.debian.org/debian

		# prepare init-script for second stage inside VM
		cat > stage1/stage2.sh << EOF
#!/bin/sh

# run second-stage bootstrap
/debootstrap/debootstrap --second-stage

# mount pseudo-filesystems
mount -vt proc proc /proc
mount -vt sysfs sysfs /sys

# configure dns
cat /proc/net/pnp > /etc/resolv.conf

# set empty root password
passwd -d root

# update command-not-found db
apt-file update
update-command-not-found

# enable optional system services
# none yet ...

# populate fstab
printf "/dev/root / ext4 defaults 0 1\\n" > /etc/fstab

# delete self
rm -f /stage2.sh

# flush disk
sync

# power-off
reboot -f
EOF
		chmod +x stage1/stage2.sh

		# create empty partition image
		dd if=/dev/zero of=rootfs.e2.orig bs=1 count=0 seek=${DEBIAN_ROOTFS_SIZE}

		# create filesystem from first stage
		mkfs.ext2 -L rootfs -E root_owner=0:0 -d stage1 rootfs.e2.orig

		# bootstrap second stage within qemu
		qemu-system-aarch64 \
			-m 1G \
			-M virt \
			-cpu cortex-a57 \
			-smp 1 \
			-netdev user,id=eth0 \
			-device virtio-net-device,netdev=eth0 \
			-drive file=rootfs.e2.orig,if=none,format=raw,id=hd0,discard=unmap \
			-device virtio-blk-device,drive=hd0 \
			-nographic \
			-no-reboot \
			-kernel "${BASE_DIR}/tmp/linux/boot/Image" \
			-append "console=ttyAMA0 root=/dev/vda rootfstype=ext2 ip=dhcp rw init=/stage2.sh" \


		:

		# convert to ext4
		tune2fs -O extents,uninit_bg,dir_index,has_journal rootfs.e2.orig
	fi;

	# export final rootfs for next steps
	cp --sparse=always rootfs.e2.orig "${BASE_DIR}/tmp/rootfs.ext4"
}
##################################################################################################################################




##################################################################################################################################
#							BUILD selected Distro
do_build_${DISTRO}
##################################################################################################################################



##################################################################################################################################
#							APPLY OVERLAY
do_overlay_rootfs() {
	if [ "x${DISTRO}" = "xbuildroot" ]; then
		# buildroot consumes overlay directory automatically as part of the build
		return 0
	fi

	if [ -d "${BASE_DIR}/overlay/${DISTRO}" ]; then
		# apply overlay (configuration + data files only - can't "chmod +x")
		# TODO: implement this step through qemu with full permissions
		find "${BASE_DIR}/overlay/${DISTRO}" -type f -printf "%P\n" | e2cp -G 0 -O 0 -s "${BASE_DIR}/overlay/${DISTRO}" -d "${BASE_DIR}/tmp/rootfs.ext4:" -a
	fi
}
do_overlay_rootfs
##################################################################################################################################




mkdir -p $BASE_DIR/output




###################################################################################################################################
#							Create Kernel & Modules Package
do_package_kernel() {
	cd ${BASE_DIR}/tmp/linux
	tar --numeric-owner --owner=0 --group=0 --create --file ${BASE_DIR}/output/linux-${COMMIT_HASH}.tar *
}
do_package_kernel
###################################################################################################################################




###################################################################################################################################
#							Generate extlinux.conf for U-Boot Distro-Boot Feature
do_generate_extlinux() {
	local PARTNUMBER=$1
	local PARTUUID=`blkid -s PTUUID -o value ${BASE_DIR}/output/${IMAGE_NAME}`
	PARTUUID=${PARTUUID}'-0'${PARTNUMBER} # specific partition uuid

	mkdir -p ${BASE_DIR}/tmp/extlinux
	cat > ${BASE_DIR}/tmp/extlinux/extlinux.conf << EOF
TIMEOUT 0
DEFAULT default
MENU TITLE SolidRun AM64 Reference BSP
LABEL default
	MENU LABEL default kernel
	LINUX ../Image
	FDTDIR ../
	APPEND earlycon=ns16550a,mmio32,0x02800000 console=ttyS2,115200n8 log_level=9 root=PARTUUID=$PARTUUID rw rootwait pcie_aspm=off
EOF
}
###################################################################################################################################




###################################################################################################################################
#							Integrate Artifacts on rootfs

echo "copying \"k3conf\" ..."
e2cp -G 0 -O 0 -P 755 -s "$BASE_DIR/tmp" -d "${BASE_DIR}/tmp/rootfs.ext4:/usr/bin" -a -v k3conf

echo "copying kernel ..."
e2cp -G 0 -O 0 -P 644 -a -d "${BASE_DIR}/tmp/rootfs.ext4:" -s "${BASE_DIR}/tmp/linux" -v boot/Image boot/ti/*.dtb

echo "copying kernel modules ..."
find "${BASE_DIR}/tmp/linux/usr/lib/modules" -type f -not -name "*.ko*" -printf "%P\n" | e2cp -G 0 -O 0 -P 644 -s "${BASE_DIR}/tmp/linux/usr/lib/modules" -d "${BASE_DIR}/tmp/rootfs.ext4:usr/lib/modules" -a
for module in ${MODULES//,/ }; do
	find "${BASE_DIR}/tmp/linux/usr/lib/modules" -type f -name "${module//[_-]/\[_-\]}.ko*" -printf "%P\n" | e2cp -G 0 -O 0 -P 644 -s "${BASE_DIR}/tmp/linux/usr/lib/modules" -d "${BASE_DIR}/tmp/rootfs.ext4:usr/lib/modules" -a -v
done
###################################################################################################################################




###################################################################################################################################
#							Create SD Image file
function do_assemble_sd() {
	local IMAGE_NAME=microsd-${COMMIT_HASH}.img

	cd $BASE_DIR
	mkdir -p "$BASE_DIR/output"

	# define partition offsets
	# note: partition start and end sectors are inclusive, add/subtract 1 where appropriate
	IMAGE_BOOTPART_START=$((1*1024*1024)) # partition start aligned to 1MiB
	IMAGE_BOOTPART_END=$((8*1024*1024-1)) # bootpart size = 7MiB
	IMAGE_ROOTPART_SIZE=`stat -c "%s" tmp/rootfs.ext4`
	IMAGE_ROOTPART_START=$((IMAGE_BOOTPART_END+1))
	IMAGE_ROOTPART_END=$((IMAGE_ROOTPART_START+IMAGE_ROOTPART_SIZE))
	IMAGE_SIZE=$((IMAGE_ROOTPART_END+512)) # require 1 additional sector at end

	# Create the output image, 2 partitions: 1 boot partition and one root partition
	dd if=/dev/zero of=$BASE_DIR/output/$IMAGE_NAME bs=1 count=0 seek=${IMAGE_SIZE}
	parted -s $BASE_DIR/output/$IMAGE_NAME -- mklabel msdos mkpart primary fat32 ${IMAGE_BOOTPART_START}B ${IMAGE_BOOTPART_END}B mkpart primary ext4 ${IMAGE_ROOTPART_START}B ${IMAGE_ROOTPART_END}B

	# mark both partitions bootable:
	# 1. for SoC Boot-ROM (tiboot3.bin on FAT part)
	# 2. for U-Boot (extlinux.conf on rootfs)
	sfdisk -A output/${IMAGE_NAME} 1 2

	# generate extlinux.conf after partition table exists and partition uuids are known
	do_generate_extlinux 2
	e2cp -G 0 -O 0 -P 644 -a -d "${BASE_DIR}/tmp/rootfs.ext4:/boot" -s "${BASE_DIR}/tmp" -v extlinux/extlinux.conf

	# Create boot partition as a different file
	dd if=/dev/zero of=$BASE_DIR/output/boot_$IMAGE_NAME bs=1M count=0 seek=7

	mformat -v boot -i $BASE_DIR/output/boot_$IMAGE_NAME ::

	mcopy -i $BASE_DIR/output/boot_$IMAGE_NAME $BASE_DIR/tmp/tispl.bin ::tispl.bin

	mcopy -i $BASE_DIR/output/boot_$IMAGE_NAME $BASE_DIR/tmp/tiboot3.bin ::tiboot3.bin

	mcopy -i $BASE_DIR/output/boot_$IMAGE_NAME $BASE_DIR/tmp/u-boot.img ::u-boot.img

	# Now find offsets in output image
	FIRST_PARTITION_OFFSET=`fdisk $BASE_DIR/output/$IMAGE_NAME -l | grep img1 | awk '{print $3}'`
	SECOND_PARTITION_OFFSET=`fdisk $BASE_DIR/output/$IMAGE_NAME -l | grep img2 | awk '{print $3}'`

	# Write boot partition into output partition
	dd if=$BASE_DIR/output/boot_$IMAGE_NAME of=$BASE_DIR/output/$IMAGE_NAME seek=$FIRST_PARTITION_OFFSET conv=sparse

	# write rootfs into second partition
	dd if=$BASE_DIR/tmp/rootfs.ext4 of=$BASE_DIR/output/$IMAGE_NAME seek=$SECOND_PARTITION_OFFSET conv=sparse
}
do_assemble_sd
###################################################################################################################################




###################################################################################################################################
#							Create eMMC Image file (rootfs)
function do_assemble_emmc_bootpart() {
	local BUNDLE="$BASE_DIR/output/boot_emmc-${COMMIT_HASH}.img"

	cd $BASE_DIR
	mkdir -p "$BASE_DIR/output"

	truncate -s 4M "$BUNDLE"
	dd of="$BUNDLE" bs=512 conv=notrunc seek=0    if="$BASE_DIR/tmp/tiboot3.bin"
	dd of="$BUNDLE" bs=512 conv=notrunc seek=1024 if="$BASE_DIR/tmp/tispl.bin"
	dd of="$BUNDLE" bs=512 conv=notrunc seek=3072 if="$BASE_DIR/tmp/u-boot.img"
}

function do_assemble_emmc() {
	local IMAGE_NAME=emmc-${COMMIT_HASH}.img

	cd $BASE_DIR
	mkdir -p "$BASE_DIR/output"

	# define partition offsets
	# note: partition start and end sectors are inclusive, add/subtract 1 where appropriate
	IMAGE_ROOTPART_SIZE=`stat -c "%s" tmp/rootfs.ext4`
	IMAGE_ROOTPART_START=$((4*1024*1024)) # partition start aligned to 4MiB
	IMAGE_ROOTPART_END=$((IMAGE_ROOTPART_START+IMAGE_ROOTPART_SIZE))
	IMAGE_SIZE=$((IMAGE_ROOTPART_END+512)) # require 1 additional sector at end

	# Create the output image, 1 partition: rootfs, no boot partition
	dd if=/dev/zero of=$BASE_DIR/output/$IMAGE_NAME bs=1 count=0 seek=${IMAGE_SIZE}
	parted -s $BASE_DIR/output/$IMAGE_NAME -- mklabel msdos mkpart primary ext4 ${IMAGE_ROOTPART_START}B ${IMAGE_ROOTPART_END}B set 1 boot on

	# generate extlinux.conf after partition table exists and partition uuids are known
	do_generate_extlinux 1
	e2cp -G 0 -O 0 -P 644 -a -d "${BASE_DIR}/tmp/rootfs.ext4:/boot" -s "${BASE_DIR}/tmp" -v extlinux/extlinux.conf

	# Now find offsets in output image
	FIRST_PARTITION_OFFSET=`fdisk $BASE_DIR/output/$IMAGE_NAME -l | grep img1 | awk '{print $3}'`

	# write rootfs into first partition
	dd if=$BASE_DIR/tmp/rootfs.ext4 of=$BASE_DIR/output/$IMAGE_NAME seek=$FIRST_PARTITION_OFFSET conv=sparse
}
do_assemble_emmc_bootpart
do_assemble_emmc
###################################################################################################################################




###################################################################################################################################
#							Print Report

printf "\n\nSD bootable image: $BASE_DIR/output/microsd-${COMMIT_HASH}.img\n\n"
printf "\n\neMMC rootfs image: $BASE_DIR/output/emmc-${COMMIT_HASH}.img\n\n"
printf "\n\neMMC bootpart image: $BASE_DIR/output/boot_emmc-${COMMIT_HASH}.img\n\n"
printf "\n\nImage file: $BASE_DIR/output/$IMAGE_NAME\n\n"
printf "\n\nKernel package: $BASE_DIR/output/linux-${COMMIT_HASH}.tar\n\n"

###################################################################################################################################
